package xxgam.oracle.apps.fa.sumaria.trx.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AdicionesVORowImpl extends OAViewRowImpl {
    public static final int JEBATCHID = 0;
    public static final int ACCOUNTEDDEBIT = 1;
    public static final int ACCOUNTEDCREDIT = 2;
    public static final int LEDGERID = 3;
    public static final int CODECOMBINATIONID = 4;
    public static final int PERIODNAME = 5;

    /**This is the default constructor (do not remove)
     */
    public AdicionesVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute JeBatchId
     */
    public String getJeBatchId() {
        return (String) getAttributeInternal(JEBATCHID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute JeBatchId
     */
    public void setJeBatchId(String value) {
        setAttributeInternal(JEBATCHID, value);
    }

    /**Gets the attribute value for the calculated attribute AccountedDebit
     */
    public Number getAccountedDebit() {
        return (Number) getAttributeInternal(ACCOUNTEDDEBIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccountedDebit
     */
    public void setAccountedDebit(Number value) {
        setAttributeInternal(ACCOUNTEDDEBIT, value);
    }

    /**Gets the attribute value for the calculated attribute AccountedCredit
     */
    public Number getAccountedCredit() {
        return (Number) getAttributeInternal(ACCOUNTEDCREDIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AccountedCredit
     */
    public void setAccountedCredit(Number value) {
        setAttributeInternal(ACCOUNTEDCREDIT, value);
    }

    /**Gets the attribute value for the calculated attribute LedgerId
     */
    public Number getLedgerId() {
        return (Number) getAttributeInternal(LEDGERID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LedgerId
     */
    public void setLedgerId(Number value) {
        setAttributeInternal(LEDGERID, value);
    }

    /**Gets the attribute value for the calculated attribute CodeCombinationId
     */
    public Number getCodeCombinationId() {
        return (Number) getAttributeInternal(CODECOMBINATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodeCombinationId
     */
    public void setCodeCombinationId(Number value) {
        setAttributeInternal(CODECOMBINATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute PeriodName
     */
    public String getPeriodName() {
        return (String) getAttributeInternal(PERIODNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute PeriodName
     */
    public void setPeriodName(String value) {
        setAttributeInternal(PERIODNAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case JEBATCHID:
            return getJeBatchId();
        case ACCOUNTEDDEBIT:
            return getAccountedDebit();
        case ACCOUNTEDCREDIT:
            return getAccountedCredit();
        case LEDGERID:
            return getLedgerId();
        case CODECOMBINATIONID:
            return getCodeCombinationId();
        case PERIODNAME:
            return getPeriodName();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
