package xxgam.oracle.apps.fa.sumaria.trx.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CodeCuentaVORowImpl extends OAViewRowImpl {
    public static final int CODECOMBINATIONID = 0;
    public static final int SEGMENT1 = 1;
    public static final int SEGMENT5 = 2;
    public static final int SEGMENT6 = 3;

    /**This is the default constructor (do not remove)
     */
    public CodeCuentaVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute CodeCombinationId
     */
    public Number getCodeCombinationId() {
        return (Number) getAttributeInternal(CODECOMBINATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CodeCombinationId
     */
    public void setCodeCombinationId(Number value) {
        setAttributeInternal(CODECOMBINATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute Segment1
     */
    public String getSegment1() {
        return (String) getAttributeInternal(SEGMENT1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment1
     */
    public void setSegment1(String value) {
        setAttributeInternal(SEGMENT1, value);
    }

    /**Gets the attribute value for the calculated attribute Segment5
     */
    public String getSegment5() {
        return (String) getAttributeInternal(SEGMENT5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment5
     */
    public void setSegment5(String value) {
        setAttributeInternal(SEGMENT5, value);
    }

    /**Gets the attribute value for the calculated attribute Segment6
     */
    public String getSegment6() {
        return (String) getAttributeInternal(SEGMENT6);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Segment6
     */
    public void setSegment6(String value) {
        setAttributeInternal(SEGMENT6, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CODECOMBINATIONID:
            return getCodeCombinationId();
        case SEGMENT1:
            return getSegment1();
        case SEGMENT5:
            return getSegment5();
        case SEGMENT6:
            return getSegment6();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
