package xxgam.oracle.apps.fa.sumaria.trx.server;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CuentasRubrosVODefImpl extends ViewDefImpl {
    public CuentasRubrosVODefImpl(String name) {
        super(name);
    }

    /**This is the default constructor (do not remove)
     */
    public CuentasRubrosVODefImpl() {
    }
}
