package xxgam.oracle.apps.fa.sumaria.trx.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InversionTrxVORowImpl extends OAViewRowImpl {
    public static final int CUENTA = 0;
    public static final int SUBCUENTA = 1;
    public static final int SALDOINICIAL = 2;
    public static final int ADICIONES = 3;
    public static final int DISMINUCIONES = 4;
    public static final int TRANSACCIONES = 5;
    public static final int BAJAS_VENTA = 6;
    public static final int BAJAS_SCRAP = 7;
    public static final int DEPRN_VENTA = 8;
    public static final int DEPRN_SCRAP = 9;
    public static final int SALDO_FINAL = 10;

    /**This is the default constructor (do not remove)
     */
    public InversionTrxVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Cuenta
     */
    public String getCuenta() {
        return (String) getAttributeInternal(CUENTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Cuenta
     */
    public void setCuenta(String value) {
        setAttributeInternal(CUENTA, value);
    }

    /**Gets the attribute value for the calculated attribute SubCuenta
     */
    public String getSubCuenta() {
        return (String) getAttributeInternal(SUBCUENTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SubCuenta
     */
    public void setSubCuenta(String value) {
        setAttributeInternal(SUBCUENTA, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUENTA:
            return getCuenta();
        case SUBCUENTA:
            return getSubCuenta();
        case SALDOINICIAL:
            return getSaldoInicial();
        case ADICIONES:
            return getAdiciones();
        case DISMINUCIONES:
            return getDisminuciones();
        case TRANSACCIONES:
            return getTransacciones();
        case BAJAS_VENTA:
            return getBajas_Venta();
        case BAJAS_SCRAP:
            return getBajas_scrap();
        case DEPRN_VENTA:
            return getDeprn_Venta();
        case DEPRN_SCRAP:
            return getDeprn_scrap();
        case SALDO_FINAL:
            return getSaldo_final();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case CUENTA:
            setCuenta((String)value);
            return;
        case SUBCUENTA:
            setSubCuenta((String)value);
            return;
        case SALDOINICIAL:
            setSaldoInicial((Number)value);
            return;
        case ADICIONES:
            setAdiciones((Number)value);
            return;
        case DISMINUCIONES:
            setDisminuciones((Number)value);
            return;
        case BAJAS_VENTA:
            setBajas_Venta((Number)value);
            return;
        case BAJAS_SCRAP:
            setBajas_scrap((Number)value);
            return;
        case DEPRN_VENTA:
            setDeprn_Venta((Number)value);
            return;
        case DEPRN_SCRAP:
            setDeprn_scrap((Number)value);
            return;
        case SALDO_FINAL:
            setSaldo_final((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute SaldoInicial
     */
    public Number getSaldoInicial() {
        return (Number) getAttributeInternal(SALDOINICIAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SaldoInicial
     */
    public void setSaldoInicial(Number value) {
        setAttributeInternal(SALDOINICIAL, value);
    }

    /**Gets the attribute value for the calculated attribute Adiciones
     */
    public Number getAdiciones() {
        return (Number) getAttributeInternal(ADICIONES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Adiciones
     */
    public void setAdiciones(Number value) {
        setAttributeInternal(ADICIONES, value);
    }

    /**Gets the attribute value for the calculated attribute Disminuciones
     */
    public Number getDisminuciones() {
        return (Number) getAttributeInternal(DISMINUCIONES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Disminuciones
     */
    public void setDisminuciones(Number value) {
        setAttributeInternal(DISMINUCIONES, value);
    }

    /**Gets the attribute value for the calculated attribute Transacciones
     */
    public String getTransacciones() {
        return (String) getAttributeInternal(TRANSACCIONES);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Transacciones
     */
    public void setTransacciones(String value) {
        setAttributeInternal(TRANSACCIONES, value);
    }

    /**Gets the attribute value for the calculated attribute Bajas_Venta
     */
    public Number getBajas_Venta() {
        return (Number) getAttributeInternal(BAJAS_VENTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Bajas_Venta
     */
    public void setBajas_Venta(Number value) {
        setAttributeInternal(BAJAS_VENTA, value);
    }


    /**Gets the attribute value for the calculated attribute Bajas_scrap
     */
    public Number getBajas_scrap() {
        return (Number) getAttributeInternal(BAJAS_SCRAP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Bajas_scrap
     */
    public void setBajas_scrap(Number value) {
        setAttributeInternal(BAJAS_SCRAP, value);
    }

    /**Gets the attribute value for the calculated attribute Deprn_Venta
     */
    public Number getDeprn_Venta() {
        return (Number) getAttributeInternal(DEPRN_VENTA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Deprn_Venta
     */
    public void setDeprn_Venta(Number value) {
        setAttributeInternal(DEPRN_VENTA, value);
    }

    /**Gets the attribute value for the calculated attribute Deprn_scrap
     */
    public Number getDeprn_scrap() {
        return (Number) getAttributeInternal(DEPRN_SCRAP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Deprn_scrap
     */
    public void setDeprn_scrap(Number value) {
        setAttributeInternal(DEPRN_SCRAP, value);
    }

    /**Gets the attribute value for the calculated attribute Saldo_final
     */
    public Number getSaldo_final() {
        return (Number) getAttributeInternal(SALDO_FINAL);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Saldo_final
     */
    public void setSaldo_final(Number value) {
        setAttributeInternal(SALDO_FINAL, value);
    }
}
