package xxgam.oracle.apps.fa.sumaria.trx.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TransfManEOImpl extends OAEntityImpl {
    public static final int ADICIONES = 0;
    public static final int ADICIONESMAN = 1;
    public static final int ATTRIBUTE1 = 2;
    public static final int ATTRIBUTE10 = 3;
    public static final int ATTRIBUTE2 = 4;
    public static final int ATTRIBUTE3 = 5;
    public static final int ATTRIBUTE4 = 6;
    public static final int ATTRIBUTE5 = 7;
    public static final int ATTRIBUTE6 = 8;
    public static final int ATTRIBUTE7 = 9;
    public static final int ATTRIBUTE9 = 10;
    public static final int ATTRIBUTECATEGORY = 11;
    public static final int BAJASINGRESO = 12;
    public static final int BAJASINGRESOMAN = 13;
    public static final int BAJAXVENTA = 14;
    public static final int BAJAXVENTAMAN = 15;
    public static final int CREATEDBY = 16;
    public static final int CREATIONDATE = 17;
    public static final int CUENTA = 18;
    public static final int CURRENCYCODE = 19;
    public static final int DISMINUCIONES = 20;
    public static final int DISMINUCIONESMAN = 21;
    public static final int DPRNEJERCICIO = 22;
    public static final int DPRNEJERCICIOMAN = 23;
    public static final int DPRNSINGRESO = 24;
    public static final int DPRNSINGRESOMAN = 25;
    public static final int DPRNXVENTA = 26;
    public static final int DPRNXVENTAMAN = 27;
    public static final int LASTUPDATEDBY = 28;
    public static final int LASTUPDATEDATE = 29;
    public static final int LASTUPDATELOGIN = 30;
    public static final int NUMRUBRO = 31;
    public static final int OPERATINGUNIT = 32;
    public static final int PERIODO = 33;
    public static final int RUBRO = 34;
    public static final int SALDOFINAL = 35;
    public static final int SALDOINI = 36;
    public static final int SALDOINIMAN = 37;
    public static final int SUBCUENTA = 38;
    public static final int SUMA = 39;
    public static final int TRANSF = 40;
    public static final int TRANSFMAN = 41;
    public static final int XSTID = 42;
    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public TransfManEOImpl() {
    }

    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxgam.oracle.apps.fa.sumaria.trx.server.TransfManEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for Adiciones, using the alias name Adiciones
     */
    public Number getAdiciones() {
        return (Number)getAttributeInternal(ADICIONES);
    }

    /**Sets <code>value</code> as the attribute value for Adiciones
     */
    public void setAdiciones(Number value) {
        setAttributeInternal(ADICIONES, value);
    }

    /**Gets the attribute value for AdicionesMan, using the alias name AdicionesMan
     */
    public Number getAdicionesMan() {
        return (Number)getAttributeInternal(ADICIONESMAN);
    }

    /**Sets <code>value</code> as the attribute value for AdicionesMan
     */
    public void setAdicionesMan(Number value) {
        setAttributeInternal(ADICIONESMAN, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute10, using the alias name Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for Attribute6, using the alias name Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**Gets the attribute value for Attribute7, using the alias name Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**Gets the attribute value for Attribute9, using the alias name Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**Gets the attribute value for AttributeCategory, using the alias name AttributeCategory
     */
    public Number getAttributeCategory() {
        return (Number)getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for AttributeCategory
     */
    public void setAttributeCategory(Number value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for BajaSIngreso, using the alias name BajaSIngreso
     */
    public Number getBajaSIngreso() {
        return (Number)getAttributeInternal(BAJASINGRESO);
    }

    /**Sets <code>value</code> as the attribute value for BajaSIngreso
     */
    public void setBajaSIngreso(Number value) {
        setAttributeInternal(BAJASINGRESO, value);
    }

    /**Gets the attribute value for BajaSIngresoMan, using the alias name BajaSIngresoMan
     */
    public Number getBajaSIngresoMan() {
        return (Number)getAttributeInternal(BAJASINGRESOMAN);
    }

    /**Sets <code>value</code> as the attribute value for BajaSIngresoMan
     */
    public void setBajaSIngresoMan(Number value) {
        setAttributeInternal(BAJASINGRESOMAN, value);
    }

    /**Gets the attribute value for BajaXVenta, using the alias name BajaXVenta
     */
    public Number getBajaXVenta() {
        return (Number)getAttributeInternal(BAJAXVENTA);
    }

    /**Sets <code>value</code> as the attribute value for BajaXVenta
     */
    public void setBajaXVenta(Number value) {
        setAttributeInternal(BAJAXVENTA, value);
    }

    /**Gets the attribute value for BajaXVentaMan, using the alias name BajaXVentaMan
     */
    public Number getBajaXVentaMan() {
        return (Number)getAttributeInternal(BAJAXVENTAMAN);
    }

    /**Sets <code>value</code> as the attribute value for BajaXVentaMan
     */
    public void setBajaXVentaMan(Number value) {
        setAttributeInternal(BAJAXVENTAMAN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for Cuenta, using the alias name Cuenta
     */
    public String getCuenta() {
        return (String)getAttributeInternal(CUENTA);
    }

    /**Sets <code>value</code> as the attribute value for Cuenta
     */
    public void setCuenta(String value) {
        setAttributeInternal(CUENTA, value);
    }

    /**Gets the attribute value for CurrencyCode, using the alias name CurrencyCode
     */
    public String getCurrencyCode() {
        return (String)getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for Disminuciones, using the alias name Disminuciones
     */
    public Number getDisminuciones() {
        return (Number)getAttributeInternal(DISMINUCIONES);
    }

    /**Sets <code>value</code> as the attribute value for Disminuciones
     */
    public void setDisminuciones(Number value) {
        setAttributeInternal(DISMINUCIONES, value);
    }

    /**Gets the attribute value for DisminucionesMan, using the alias name DisminucionesMan
     */
    public Number getDisminucionesMan() {
        return (Number)getAttributeInternal(DISMINUCIONESMAN);
    }

    /**Sets <code>value</code> as the attribute value for DisminucionesMan
     */
    public void setDisminucionesMan(Number value) {
        setAttributeInternal(DISMINUCIONESMAN, value);
    }

    /**Gets the attribute value for DprnEjercicio, using the alias name DprnEjercicio
     */
    public Number getDprnEjercicio() {
        return (Number)getAttributeInternal(DPRNEJERCICIO);
    }

    /**Sets <code>value</code> as the attribute value for DprnEjercicio
     */
    public void setDprnEjercicio(Number value) {
        setAttributeInternal(DPRNEJERCICIO, value);
    }

    /**Gets the attribute value for DprnEjercicioMan, using the alias name DprnEjercicioMan
     */
    public Number getDprnEjercicioMan() {
        return (Number)getAttributeInternal(DPRNEJERCICIOMAN);
    }

    /**Sets <code>value</code> as the attribute value for DprnEjercicioMan
     */
    public void setDprnEjercicioMan(Number value) {
        setAttributeInternal(DPRNEJERCICIOMAN, value);
    }

    /**Gets the attribute value for DprnSIngreso, using the alias name DprnSIngreso
     */
    public Number getDprnSIngreso() {
        return (Number)getAttributeInternal(DPRNSINGRESO);
    }

    /**Sets <code>value</code> as the attribute value for DprnSIngreso
     */
    public void setDprnSIngreso(Number value) {
        setAttributeInternal(DPRNSINGRESO, value);
    }

    /**Gets the attribute value for DprnSIngresoMan, using the alias name DprnSIngresoMan
     */
    public Number getDprnSIngresoMan() {
        return (Number)getAttributeInternal(DPRNSINGRESOMAN);
    }

    /**Sets <code>value</code> as the attribute value for DprnSIngresoMan
     */
    public void setDprnSIngresoMan(Number value) {
        setAttributeInternal(DPRNSINGRESOMAN, value);
    }

    /**Gets the attribute value for DprnXVenta, using the alias name DprnXVenta
     */
    public Number getDprnXVenta() {
        return (Number)getAttributeInternal(DPRNXVENTA);
    }

    /**Sets <code>value</code> as the attribute value for DprnXVenta
     */
    public void setDprnXVenta(Number value) {
        setAttributeInternal(DPRNXVENTA, value);
    }

    /**Gets the attribute value for DprnXVentaMan, using the alias name DprnXVentaMan
     */
    public Number getDprnXVentaMan() {
        return (Number)getAttributeInternal(DPRNXVENTAMAN);
    }

    /**Sets <code>value</code> as the attribute value for DprnXVentaMan
     */
    public void setDprnXVentaMan(Number value) {
        setAttributeInternal(DPRNXVENTAMAN, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for NumRubro, using the alias name NumRubro
     */
    public String getNumRubro() {
        return (String)getAttributeInternal(NUMRUBRO);
    }

    /**Sets <code>value</code> as the attribute value for NumRubro
     */
    public void setNumRubro(String value) {
        setAttributeInternal(NUMRUBRO, value);
    }

    /**Gets the attribute value for OperatingUnit, using the alias name OperatingUnit
     */
    public String getOperatingUnit() {
        return (String)getAttributeInternal(OPERATINGUNIT);
    }

    /**Sets <code>value</code> as the attribute value for OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**Gets the attribute value for Periodo, using the alias name Periodo
     */
    public String getPeriodo() {
        return (String)getAttributeInternal(PERIODO);
    }

    /**Sets <code>value</code> as the attribute value for Periodo
     */
    public void setPeriodo(String value) {
        setAttributeInternal(PERIODO, value);
    }

    /**Gets the attribute value for Rubro, using the alias name Rubro
     */
    public String getRubro() {
        return (String)getAttributeInternal(RUBRO);
    }

    /**Sets <code>value</code> as the attribute value for Rubro
     */
    public void setRubro(String value) {
        setAttributeInternal(RUBRO, value);
    }

    /**Gets the attribute value for SaldoFinal, using the alias name SaldoFinal
     */
    public Number getSaldoFinal() {
        return (Number)getAttributeInternal(SALDOFINAL);
    }

    /**Sets <code>value</code> as the attribute value for SaldoFinal
     */
    public void setSaldoFinal(Number value) {
        setAttributeInternal(SALDOFINAL, value);
    }

    /**Gets the attribute value for SaldoIni, using the alias name SaldoIni
     */
    public Number getSaldoIni() {
        return (Number)getAttributeInternal(SALDOINI);
    }

    /**Sets <code>value</code> as the attribute value for SaldoIni
     */
    public void setSaldoIni(Number value) {
        setAttributeInternal(SALDOINI, value);
    }

    /**Gets the attribute value for SaldoIniMan, using the alias name SaldoIniMan
     */
    public Number getSaldoIniMan() {
        return (Number)getAttributeInternal(SALDOINIMAN);
    }

    /**Sets <code>value</code> as the attribute value for SaldoIniMan
     */
    public void setSaldoIniMan(Number value) {
        setAttributeInternal(SALDOINIMAN, value);
    }

    /**Gets the attribute value for Subcuenta, using the alias name Subcuenta
     */
    public String getSubcuenta() {
        return (String)getAttributeInternal(SUBCUENTA);
    }

    /**Sets <code>value</code> as the attribute value for Subcuenta
     */
    public void setSubcuenta(String value) {
        setAttributeInternal(SUBCUENTA, value);
    }

    /**Gets the attribute value for Suma, using the alias name Suma
     */
    public Number getSuma() {
        return (Number)getAttributeInternal(SUMA);
    }

    /**Sets <code>value</code> as the attribute value for Suma
     */
    public void setSuma(Number value) {
        setAttributeInternal(SUMA, value);
    }

    /**Gets the attribute value for Transf, using the alias name Transf
     */
    public Number getTransf() {
        return (Number)getAttributeInternal(TRANSF);
    }

    /**Sets <code>value</code> as the attribute value for Transf
     */
    public void setTransf(Number value) {
        setAttributeInternal(TRANSF, value);
    }

    /**Gets the attribute value for TransfMan, using the alias name TransfMan
     */
    public Number getTransfMan() {
        return (Number)getAttributeInternal(TRANSFMAN);
    }

    /**Sets <code>value</code> as the attribute value for TransfMan
     */
    public void setTransfMan(Number value) {
        setAttributeInternal(TRANSFMAN, value);
    }

    /**Gets the attribute value for XstId, using the alias name XstId
     */
    public Number getXstId() {
        return (Number)getAttributeInternal(XSTID);
    }

    /**Sets <code>value</code> as the attribute value for XstId
     */
    public void setXstId(Number value) {
        setAttributeInternal(XSTID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ADICIONES:
            return getAdiciones();
        case ADICIONESMAN:
            return getAdicionesMan();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE10:
            return getAttribute10();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case ATTRIBUTE6:
            return getAttribute6();
        case ATTRIBUTE7:
            return getAttribute7();
        case ATTRIBUTE9:
            return getAttribute9();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case BAJASINGRESO:
            return getBajaSIngreso();
        case BAJASINGRESOMAN:
            return getBajaSIngresoMan();
        case BAJAXVENTA:
            return getBajaXVenta();
        case BAJAXVENTAMAN:
            return getBajaXVentaMan();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CUENTA:
            return getCuenta();
        case CURRENCYCODE:
            return getCurrencyCode();
        case DISMINUCIONES:
            return getDisminuciones();
        case DISMINUCIONESMAN:
            return getDisminucionesMan();
        case DPRNEJERCICIO:
            return getDprnEjercicio();
        case DPRNEJERCICIOMAN:
            return getDprnEjercicioMan();
        case DPRNSINGRESO:
            return getDprnSIngreso();
        case DPRNSINGRESOMAN:
            return getDprnSIngresoMan();
        case DPRNXVENTA:
            return getDprnXVenta();
        case DPRNXVENTAMAN:
            return getDprnXVentaMan();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case NUMRUBRO:
            return getNumRubro();
        case OPERATINGUNIT:
            return getOperatingUnit();
        case PERIODO:
            return getPeriodo();
        case RUBRO:
            return getRubro();
        case SALDOFINAL:
            return getSaldoFinal();
        case SALDOINI:
            return getSaldoIni();
        case SALDOINIMAN:
            return getSaldoIniMan();
        case SUBCUENTA:
            return getSubcuenta();
        case SUMA:
            return getSuma();
        case TRANSF:
            return getTransf();
        case TRANSFMAN:
            return getTransfMan();
        case XSTID:
            return getXstId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ADICIONES:
            setAdiciones((Number)value);
            return;
        case ADICIONESMAN:
            setAdicionesMan((Number)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE10:
            setAttribute10((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case ATTRIBUTE6:
            setAttribute6((String)value);
            return;
        case ATTRIBUTE7:
            setAttribute7((String)value);
            return;
        case ATTRIBUTE9:
            setAttribute9((String)value);
            return;
        case ATTRIBUTECATEGORY:
            setAttributeCategory((Number)value);
            return;
        case BAJASINGRESO:
            setBajaSIngreso((Number)value);
            return;
        case BAJASINGRESOMAN:
            setBajaSIngresoMan((Number)value);
            return;
        case BAJAXVENTA:
            setBajaXVenta((Number)value);
            return;
        case BAJAXVENTAMAN:
            setBajaXVentaMan((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CUENTA:
            setCuenta((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case DISMINUCIONES:
            setDisminuciones((Number)value);
            return;
        case DISMINUCIONESMAN:
            setDisminucionesMan((Number)value);
            return;
        case DPRNEJERCICIO:
            setDprnEjercicio((Number)value);
            return;
        case DPRNEJERCICIOMAN:
            setDprnEjercicioMan((Number)value);
            return;
        case DPRNSINGRESO:
            setDprnSIngreso((Number)value);
            return;
        case DPRNSINGRESOMAN:
            setDprnSIngresoMan((Number)value);
            return;
        case DPRNXVENTA:
            setDprnXVenta((Number)value);
            return;
        case DPRNXVENTAMAN:
            setDprnXVentaMan((Number)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case NUMRUBRO:
            setNumRubro((String)value);
            return;
        case OPERATINGUNIT:
            setOperatingUnit((String)value);
            return;
        case PERIODO:
            setPeriodo((String)value);
            return;
        case RUBRO:
            setRubro((String)value);
            return;
        case SALDOFINAL:
            setSaldoFinal((Number)value);
            return;
        case SALDOINI:
            setSaldoIni((Number)value);
            return;
        case SALDOINIMAN:
            setSaldoIniMan((Number)value);
            return;
        case SUBCUENTA:
            setSubcuenta((String)value);
            return;
        case SUMA:
            setSuma((Number)value);
            return;
        case TRANSF:
            setTransf((Number)value);
            return;
        case TRANSFMAN:
            setTransfMan((Number)value);
            return;
        case XSTID:
            setXstId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number xstId) {
        return new Key(new Object[]{xstId});
    }
}
