package xxgam.oracle.apps.fa.sumaria.setup.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamRubroVORowImpl extends OAViewRowImpl {
    public static final int ID = 0;
    public static final int RUBRO = 1;

    /**This is the default constructor (do not remove)
     */
    public XxGamRubroVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**Gets the attribute value for the calculated attribute Rubro
     */
    public String getRubro() {
        return (String) getAttributeInternal(RUBRO);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Rubro
     */
    public void setRubro(String value) {
        setAttributeInternal(RUBRO, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ID:
            return getId();
        case RUBRO:
            return getRubro();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
