package xxgam.oracle.apps.fa.sumaria.setup.server;

import java.sql.SQLException;

import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.OAViewObject;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;

import oracle.apps.fnd.framework.server.OADBTransaction;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;

import xxgam.oracle.apps.fa.sumaria.setup.lov.server.XxGamCuentaVOImpl;
import xxgam.oracle.apps.fa.sumaria.setup.lov.server.XxGamRubroVOImpl;
import xxgam.oracle.apps.fa.sumaria.setup.lov.server.XxGamSubcuentaVOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamSetupAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public XxGamSetupAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.fa.sumaria.setup.server", /* package name */
      "XxGamSetupAMLocal" /* Configuration Name */);
    }
    
    public void consulta(){
                XxGamSetupVOImpl vo = (XxGamSetupVOImpl)getXxGamSetupVO1();
                try {
                System.out.println("Realizando Consulta");
                vo.setWhereClause(null);
                System.out.println("search query - " + vo.getQuery());
                vo.executeQuery();
                }
                catch(Exception e) {
                         throw new OAException(e.getMessage(),OAException.ERROR);
                     }
                
                RowSetIterator rowSetIterator = vo.createRowSetIterator(null); 
                while (rowSetIterator.hasNext()) {
                      XxGamSetupVORowImpl SetupVORow = (XxGamSetupVORowImpl)rowSetIterator.next();
                                          SetupVORow.setIsRecordEnabled(true);
                                          SetupVORow.setIsRecordEnabled2(true);           
                    }
                   
                         
            }
            
    public void createRecord()
            {
              System.out.println("Creando Registro");
              OAViewObject vo = (OAViewObject)getXxGamSetupVO1();
              OADBTransaction oADBTransaction = this.getOADBTransaction();
              
              oracle.jbo.domain.Number IdSetupNum = oADBTransaction.getSequenceValue("XXGAM_SAF_SETUP_S");
             
              if (!vo.isPreparedForExecution()) 
              { 
                    vo.executeQuery(); 
              }
             
              Row row = vo.createRow();
               
              vo.insertRow(row);
              /*row.setNewRowState(Row.STATUS_INITIALIZED);*/
              row.setAttribute("IdSetup",IdSetupNum);
                row.setNewRowState(Row.STATUS_NEW);   
              /** getOADBTransaction().commit(); **/
               getOADBTransaction().postChanges();
              System.out.println("Permitiendo modificaciones al registro");
                         
                vo.executeQuery();
              
                RowSetIterator rowSetIterator = vo.createRowSetIterator(null); 
                while (rowSetIterator.hasNext()) {
                      XxGamSetupVORowImpl XxGamSetupVORow = (XxGamSetupVORowImpl)rowSetIterator.next();
                     if (XxGamSetupVORow.getIdSetup().equals(IdSetupNum)){
                         XxGamSetupVORow.setIsRecordEnabled(false);
                         XxGamSetupVORow.setIsRecordEnabled2(true);
                     } else{
                         XxGamSetupVORow.setIsRecordEnabled(true);
                         XxGamSetupVORow.setIsRecordEnabled2(true);
                     }
                    }
              
            } 
    
    public void Save(){
            
            getOADBTransaction().commit();
            
            OAViewObject vo = (OAViewObject)getXxGamSetupVO1();

            vo.executeQuery();
            
            RowSetIterator rowSetIterator = vo.createRowSetIterator(null); 
            while (rowSetIterator.hasNext()) {
                  XxGamSetupVORowImpl SetupVORow = (XxGamSetupVORowImpl)rowSetIterator.next();
                  SetupVORow.setIsRecordEnabled(true);
                  SetupVORow.setIsRecordEnabled2(true);
                  }
            
            
        }
        
    public void deleteRecord(String IdSetup)
            {
              System.out.println("Borrar Registro");
              OAViewObject vo = (OAViewObject)getXxGamSetupVO1();
              OADBTransaction oADBTransaction = this.getOADBTransaction();
              
                oracle.jbo.domain.Number numIdSetup=null;
                  try {
                      numIdSetup = new oracle.jbo.domain.Number(IdSetup);
                  } catch (SQLException sqle) {
                      throw new OAException(sqle.getMessage(),OAException.ERROR); 
                  }
             
              if (!vo.isPreparedForExecution()) 
              { 
                    vo.executeQuery(); 
              }
             
                vo.setWhereClause("ID_SETUP="+ numIdSetup);
                System.out.println("search query - " + vo.getQuery());
                vo.executeQuery();
                while (vo.hasNext()) {
                      vo.next();
                      vo.removeCurrentRow();
                    }
                            
                getOADBTransaction().commit();
              System.out.println("Registro Borrado");
            }    
            
    public void updateRecord(String IdSetup){
            
            System.out.println("Actualizando Registro");
            OAViewObject vo = (OAViewObject)getXxGamSetupVO1();
            OADBTransaction oADBTransaction = this.getOADBTransaction();
            
              oracle.jbo.domain.Number numIdSetup=null;
                try {
                    numIdSetup = new oracle.jbo.domain.Number(IdSetup);
                } catch (SQLException sqle) {
                    throw new OAException(sqle.getMessage(),OAException.ERROR); 
                }
                
            
              RowSetIterator rowSetIterator = vo.createRowSetIterator(null); 
              while (rowSetIterator.hasNext()) {
                    XxGamSetupVORowImpl SetupVORow = (XxGamSetupVORowImpl)rowSetIterator.next();
                   if (SetupVORow.getIdSetup().equals(numIdSetup)){
                       SetupVORow.setIsRecordEnabled(false);
                       SetupVORow.setIsRecordEnabled2(true);
                   }
                  }

        }


    /**Container's getter for XxGamCuentaVO1
     */
    public XxGamCuentaVOImpl getXxGamCuentaVO1() {
        return (XxGamCuentaVOImpl)findViewObject("XxGamCuentaVO1");
    }

    /**Container's getter for XxGamSubcuentaVO1
     */
    public XxGamSubcuentaVOImpl getXxGamSubcuentaVO1() {
        return (XxGamSubcuentaVOImpl)findViewObject("XxGamSubcuentaVO1");
    }

    /**Container's getter for XxGamRubroVO1
     */
    public XxGamRubroVOImpl getXxGamRubroVO1() {
        return (XxGamRubroVOImpl)findViewObject("XxGamRubroVO1");
    }

    /**Container's getter for XxGamAgrupadoVO1
     */
    public XxGamAgrupadoVOImpl getXxGamAgrupadoVO1() {
        return (XxGamAgrupadoVOImpl)findViewObject("XxGamAgrupadoVO1");
    }

    /**Container's getter for XxGamSetupVO1
     */
    public XxGamSetupVOImpl getXxGamSetupVO1() {
        return (XxGamSetupVOImpl)findViewObject("XxGamSetupVO1");
    }
}
