package xxgam.oracle.apps.fa.sumaria.setup.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;

import xxgam.oracle.apps.fa.sumaria.setup.schema.server.XxGamSetupEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamSetupVORowImpl extends OAViewRowImpl {
    public static final int IDSETUP = 0;
    public static final int CUENTA = 1;
    public static final int DESCRIPCIONCUENTA = 2;
    public static final int SUBCUENTA = 3;
    public static final int DESCRIPCIONSUBCUENTA = 4;
    public static final int RUBRO = 5;
    public static final int IDRUBRO = 6;
    public static final int CREATEDBY = 7;
    public static final int CREATIONDATE = 8;
    public static final int LASTUPDATEDBY = 9;
    public static final int LASTUPDATEDATE = 10;
    public static final int LASTUPDATELOGIN = 11;
    public static final int REQUESTID = 12;
    public static final int PROGRAMAPPLICATIONID = 13;
    public static final int PROGRAMID = 14;
    public static final int PROGRAMUPDATEDATE = 15;
    public static final int AGRUPADO = 16;
    public static final int EXCEPTIONRUBRO = 17;
    public static final int EXCEPTIONIDRUBRO = 18;
    public static final int ROWID = 19;
    public static final int ISRECORDENABLED = 20;
    public static final int ISRECORDENABLED2 = 21;

    /**This is the default constructor (do not remove)
     */
    public XxGamSetupVORowImpl() {
    }

    /**Gets XxGamSetupEO entity object.
     */
    public XxGamSetupEOImpl getXxGamSetupEO() {
        return (XxGamSetupEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ID_SETUP using the alias name IdSetup
     */
    public Number getIdSetup() {
        return (Number) getAttributeInternal(IDSETUP);
    }

    /**Sets <code>value</code> as attribute value for ID_SETUP using the alias name IdSetup
     */
    public void setIdSetup(Number value) {
        setAttributeInternal(IDSETUP, value);
    }

    /**Gets the attribute value for CUENTA using the alias name Cuenta
     */
    public String getCuenta() {
        return (String) getAttributeInternal(CUENTA);
    }

    /**Sets <code>value</code> as attribute value for CUENTA using the alias name Cuenta
     */
    public void setCuenta(String value) {
        setAttributeInternal(CUENTA, value);
    }

    /**Gets the attribute value for DESCRIPCION_CUENTA using the alias name DescripcionCuenta
     */
    public String getDescripcionCuenta() {
        return (String) getAttributeInternal(DESCRIPCIONCUENTA);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPCION_CUENTA using the alias name DescripcionCuenta
     */
    public void setDescripcionCuenta(String value) {
        setAttributeInternal(DESCRIPCIONCUENTA, value);
    }

    /**Gets the attribute value for SUBCUENTA using the alias name Subcuenta
     */
    public String getSubcuenta() {
        return (String) getAttributeInternal(SUBCUENTA);
    }

    /**Sets <code>value</code> as attribute value for SUBCUENTA using the alias name Subcuenta
     */
    public void setSubcuenta(String value) {
        setAttributeInternal(SUBCUENTA, value);
    }

    /**Gets the attribute value for DESCRIPCION_SUBCUENTA using the alias name DescripcionSubcuenta
     */
    public String getDescripcionSubcuenta() {
        return (String) getAttributeInternal(DESCRIPCIONSUBCUENTA);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPCION_SUBCUENTA using the alias name DescripcionSubcuenta
     */
    public void setDescripcionSubcuenta(String value) {
        setAttributeInternal(DESCRIPCIONSUBCUENTA, value);
    }

    /**Gets the attribute value for RUBRO using the alias name Rubro
     */
    public String getRubro() {
        return (String) getAttributeInternal(RUBRO);
    }

    /**Sets <code>value</code> as attribute value for RUBRO using the alias name Rubro
     */
    public void setRubro(String value) {
        setAttributeInternal(RUBRO, value);
    }

    /**Gets the attribute value for ID_RUBRO using the alias name IdRubro
     */
    public String getIdRubro() {
        return (String) getAttributeInternal(IDRUBRO);
    }

    /**Sets <code>value</code> as attribute value for ID_RUBRO using the alias name IdRubro
     */
    public void setIdRubro(String value) {
        setAttributeInternal(IDRUBRO, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for REQUEST_ID using the alias name RequestId
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**Sets <code>value</code> as attribute value for REQUEST_ID using the alias name RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**Gets the attribute value for PROGRAM_APPLICATION_ID using the alias name ProgramApplicationId
     */
    public Number getProgramApplicationId() {
        return (Number) getAttributeInternal(PROGRAMAPPLICATIONID);
    }

    /**Sets <code>value</code> as attribute value for PROGRAM_APPLICATION_ID using the alias name ProgramApplicationId
     */
    public void setProgramApplicationId(Number value) {
        setAttributeInternal(PROGRAMAPPLICATIONID, value);
    }

    /**Gets the attribute value for PROGRAM_ID using the alias name ProgramId
     */
    public Number getProgramId() {
        return (Number) getAttributeInternal(PROGRAMID);
    }

    /**Sets <code>value</code> as attribute value for PROGRAM_ID using the alias name ProgramId
     */
    public void setProgramId(Number value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**Gets the attribute value for PROGRAM_UPDATE_DATE using the alias name ProgramUpdateDate
     */
    public Date getProgramUpdateDate() {
        return (Date) getAttributeInternal(PROGRAMUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for PROGRAM_UPDATE_DATE using the alias name ProgramUpdateDate
     */
    public void setProgramUpdateDate(Date value) {
        setAttributeInternal(PROGRAMUPDATEDATE, value);
    }

    /**Gets the attribute value for AGRUPADO using the alias name Agrupado
     */
    public String getAgrupado() {
        return (String) getAttributeInternal(AGRUPADO);
    }

    /**Sets <code>value</code> as attribute value for AGRUPADO using the alias name Agrupado
     */
    public void setAgrupado(String value) {
        setAttributeInternal(AGRUPADO, value);
    }

    /**Gets the attribute value for EXCEPTION_RUBRO using the alias name ExceptionRubro
     */
    public String getExceptionRubro() {
        return (String) getAttributeInternal(EXCEPTIONRUBRO);
    }

    /**Sets <code>value</code> as attribute value for EXCEPTION_RUBRO using the alias name ExceptionRubro
     */
    public void setExceptionRubro(String value) {
        setAttributeInternal(EXCEPTIONRUBRO, value);
    }

    /**Gets the attribute value for EXCEPTION_ID_RUBRO using the alias name ExceptionIdRubro
     */
    public String getExceptionIdRubro() {
        return (String) getAttributeInternal(EXCEPTIONIDRUBRO);
    }

    /**Sets <code>value</code> as attribute value for EXCEPTION_ID_RUBRO using the alias name ExceptionIdRubro
     */
    public void setExceptionIdRubro(String value) {
        setAttributeInternal(EXCEPTIONIDRUBRO, value);
    }

    /**Gets the attribute value for ROWID using the alias name RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDSETUP:
            return getIdSetup();
        case CUENTA:
            return getCuenta();
        case DESCRIPCIONCUENTA:
            return getDescripcionCuenta();
        case SUBCUENTA:
            return getSubcuenta();
        case DESCRIPCIONSUBCUENTA:
            return getDescripcionSubcuenta();
        case RUBRO:
            return getRubro();
        case IDRUBRO:
            return getIdRubro();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case REQUESTID:
            return getRequestId();
        case PROGRAMAPPLICATIONID:
            return getProgramApplicationId();
        case PROGRAMID:
            return getProgramId();
        case PROGRAMUPDATEDATE:
            return getProgramUpdateDate();
        case AGRUPADO:
            return getAgrupado();
        case EXCEPTIONRUBRO:
            return getExceptionRubro();
        case EXCEPTIONIDRUBRO:
            return getExceptionIdRubro();
        case ROWID:
            return getRowID();
        case ISRECORDENABLED:
            return getIsRecordEnabled();
        case ISRECORDENABLED2:
            return getIsRecordEnabled2();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case IDSETUP:
            setIdSetup((Number)value);
            return;
        case CUENTA:
            setCuenta((String)value);
            return;
        case DESCRIPCIONCUENTA:
            setDescripcionCuenta((String)value);
            return;
        case SUBCUENTA:
            setSubcuenta((String)value);
            return;
        case DESCRIPCIONSUBCUENTA:
            setDescripcionSubcuenta((String)value);
            return;
        case RUBRO:
            setRubro((String)value);
            return;
        case IDRUBRO:
            setIdRubro((String)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case REQUESTID:
            setRequestId((Number)value);
            return;
        case PROGRAMAPPLICATIONID:
            setProgramApplicationId((Number)value);
            return;
        case PROGRAMID:
            setProgramId((Number)value);
            return;
        case PROGRAMUPDATEDATE:
            setProgramUpdateDate((Date)value);
            return;
        case AGRUPADO:
            setAgrupado((String)value);
            return;
        case EXCEPTIONRUBRO:
            setExceptionRubro((String)value);
            return;
        case EXCEPTIONIDRUBRO:
            setExceptionIdRubro((String)value);
            return;
        case ISRECORDENABLED:
            setIsRecordEnabled((Boolean)value);
            return;
        case ISRECORDENABLED2:
            setIsRecordEnabled2((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled
     */
    public Boolean getIsRecordEnabled() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled
     */
    public void setIsRecordEnabled(Boolean value) {
        setAttributeInternal(ISRECORDENABLED, value);
    }

    /**Gets the attribute value for the calculated attribute IsRecordEnabled2
     */
    public Boolean getIsRecordEnabled2() {
        return (Boolean) getAttributeInternal(ISRECORDENABLED2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute IsRecordEnabled2
     */
    public void setIsRecordEnabled2(Boolean value) {
        setAttributeInternal(ISRECORDENABLED2, value);
    }
}
