package xxgam.oracle.apps.fa.sumaria.inquiry.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamSafOmTblVORowImpl extends OAViewRowImpl {
    public static final int SAFOMID = 0;
    public static final int OPERATINGUNIT = 1;
    public static final int PERIOD = 2;
    public static final int STARTPERIOD = 3;
    public static final int ENDPERIOD = 4;
    public static final int CURRENCYCODE = 5;
    public static final int XMLSTRING = 6;
    public static final int LASTUPDATEDATE = 7;
    public static final int LASTUPDATEDBY = 8;
    public static final int LASTUPDATELOGIN = 9;
    public static final int CREATEDBY = 10;
    public static final int CREATIONDATE = 11;
    public static final int REQUESTID = 12;
    public static final int PROGRAMAPPLICATIONID = 13;
    public static final int PROGRAMID = 14;
    public static final int PROGRAMUPDATEDATE = 15;
    public static final int ATTRIBUTECATEGORY = 16;
    public static final int ATTRIBUTE1 = 17;
    public static final int ATTRIBUTE2 = 18;
    public static final int ATTRIBUTE3 = 19;
    public static final int ATTRIBUTE4 = 20;
    public static final int ATTRIBUTE5 = 21;

    /**This is the default constructor (do not remove)
     */
    public XxGamSafOmTblVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SafOmId
     */
    public Number getSafOmId() {
        return (Number) getAttributeInternal(SAFOMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SafOmId
     */
    public void setSafOmId(Number value) {
        setAttributeInternal(SAFOMID, value);
    }

    /**Gets the attribute value for the calculated attribute OperatingUnit
     */
    public String getOperatingUnit() {
        return (String) getAttributeInternal(OPERATINGUNIT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**Gets the attribute value for the calculated attribute Period
     */
    public String getPeriod() {
        return (String) getAttributeInternal(PERIOD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Period
     */
    public void setPeriod(String value) {
        setAttributeInternal(PERIOD, value);
    }

    /**Gets the attribute value for the calculated attribute StartPeriod
     */
    public Date getStartPeriod() {
        return (Date) getAttributeInternal(STARTPERIOD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute StartPeriod
     */
    public void setStartPeriod(Date value) {
        setAttributeInternal(STARTPERIOD, value);
    }

    /**Gets the attribute value for the calculated attribute EndPeriod
     */
    public Date getEndPeriod() {
        return (Date) getAttributeInternal(ENDPERIOD);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EndPeriod
     */
    public void setEndPeriod(Date value) {
        setAttributeInternal(ENDPERIOD, value);
    }

    /**Gets the attribute value for the calculated attribute CurrencyCode
     */
    public String getCurrencyCode() {
        return (String) getAttributeInternal(CURRENCYCODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
     */
    public void setCurrencyCode(String value) {
        setAttributeInternal(CURRENCYCODE, value);
    }

    /**Gets the attribute value for the calculated attribute XmlString
     */
    public ClobDomain getXmlString() {
        return (ClobDomain) getAttributeInternal(XMLSTRING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute XmlString
     */
    public void setXmlString(ClobDomain value) {
        setAttributeInternal(XMLSTRING, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for the calculated attribute CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for the calculated attribute CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute RequestId
     */
    public Number getRequestId() {
        return (Number) getAttributeInternal(REQUESTID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute RequestId
     */
    public void setRequestId(Number value) {
        setAttributeInternal(REQUESTID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramApplicationId
     */
    public Number getProgramApplicationId() {
        return (Number) getAttributeInternal(PROGRAMAPPLICATIONID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramApplicationId
     */
    public void setProgramApplicationId(Number value) {
        setAttributeInternal(PROGRAMAPPLICATIONID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramId
     */
    public Number getProgramId() {
        return (Number) getAttributeInternal(PROGRAMID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramId
     */
    public void setProgramId(Number value) {
        setAttributeInternal(PROGRAMID, value);
    }

    /**Gets the attribute value for the calculated attribute ProgramUpdateDate
     */
    public Date getProgramUpdateDate() {
        return (Date) getAttributeInternal(PROGRAMUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ProgramUpdateDate
     */
    public void setProgramUpdateDate(Date value) {
        setAttributeInternal(PROGRAMUPDATEDATE, value);
    }

    /**Gets the attribute value for the calculated attribute AttributeCategory
     */
    public String getAttributeCategory() {
        return (String) getAttributeInternal(ATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute AttributeCategory
     */
    public void setAttributeCategory(String value) {
        setAttributeInternal(ATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for the calculated attribute Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SAFOMID:
            return getSafOmId();
        case OPERATINGUNIT:
            return getOperatingUnit();
        case PERIOD:
            return getPeriod();
        case STARTPERIOD:
            return getStartPeriod();
        case ENDPERIOD:
            return getEndPeriod();
        case CURRENCYCODE:
            return getCurrencyCode();
        case XMLSTRING:
            return getXmlString();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case REQUESTID:
            return getRequestId();
        case PROGRAMAPPLICATIONID:
            return getProgramApplicationId();
        case PROGRAMID:
            return getProgramId();
        case PROGRAMUPDATEDATE:
            return getProgramUpdateDate();
        case ATTRIBUTECATEGORY:
            return getAttributeCategory();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
