package xxgam.oracle.apps.fa.sumaria.trx.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TrxLOVAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public TrxLOVAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.fa.sumaria.trx.lov.server", /* package name */
      "TrxLOVAMLocal" /* Configuration Name */);
    }

    /**Container's getter for PeriodoLOVVO1
     */
    public PeriodoLOVVOImpl getPeriodoLOVVO1() {
        return (PeriodoLOVVOImpl)findViewObject("PeriodoLOVVO1");
    }
}
