package xxgam.oracle.apps.fa.sumaria.inquiry.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamDivisaVORowImpl extends OAViewRowImpl {

    public static final int NAME = 0;
    public static final int DIVISA = 1;

    /**This is the default constructor (do not remove)
     */
    public XxGamDivisaVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case NAME:
            return getName();
        case DIVISA:
            return getDivisa();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case DIVISA:
            setDivisa((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the attribute value for the calculated attribute Divisa
     */
    public String getDivisa() {
        return (String) getAttributeInternal(DIVISA);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Divisa
     */
    public void setDivisa(String value) {
        setAttributeInternal(DIVISA, value);
    }
}
