package xxgam.oracle.apps.fa.sumaria.inquiry.lov.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamInquiryLovAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public XxGamInquiryLovAMImpl() {
    }


    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("xxgam.oracle.apps.fa.sumaria.inquiry.lov.server", /* package name */
      "XxGamInquiryLovAMLocal" /* Configuration Name */);
    }

    /**Container's getter for XxGamUnidadOperativaVO1
     */
    public OAViewObjectImpl getXxGamUnidadOperativaVO1() {
        return (OAViewObjectImpl)findViewObject("XxGamUnidadOperativaVO1");
    }

    /**Container's getter for XxGamPeriodoVO1
     */
    public OAViewObjectImpl getXxGamPeriodoVO1() {
        return (OAViewObjectImpl)findViewObject("XxGamPeriodoVO1");
    }

    /**Container's getter for XxGamDivisaVO1
     */
    public OAViewObjectImpl getXxGamDivisaVO1() {
        return (OAViewObjectImpl)findViewObject("XxGamDivisaVO1");
    }
}
