package xxgam.oracle.apps.fa.sumaria.inquiry.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxGamUnidadOperativaVORowImpl extends OAViewRowImpl {
    public static final int ORGANIZACION = 0;
    public static final int ID = 1;

    /**This is the default constructor (do not remove)
     */
    public XxGamUnidadOperativaVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Organizacion
     */
    public String getOrganizacion() {
        return (String) getAttributeInternal(ORGANIZACION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Organizacion
     */
    public void setOrganizacion(String value) {
        setAttributeInternal(ORGANIZACION, value);
    }

    /**Gets the attribute value for the calculated attribute Id
     */
    public String getId() {
        return (String) getAttributeInternal(ID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ORGANIZACION:
            return getOrganizacion();
        case ID:
            return getId();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
